name: Kody
version: '${version}'
main: dev.nxms.codes.Codes
api-version: '1.21'
author: nxmsdev
description: Plugin do zarządzania kodami promocyjnymi

softdepend:
  - LuckPerms

permissions:
  codes.admin:
    description: Dostęp do komend administracyjnych
    default: op
  codes.player:
    description: Dostęp do używania kodów
    default: true

commands:
  kod:
    description: Główna komenda pluginu Codes
    usage: /<command> [stworz|usun|lista|info|pomoc]